name: FRED x Azure SQL Database Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event_name == 'push' && github.event.head_commit.modified_files contains './database' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure SQL Database
      uses: Azure/sql-action@v1.2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './database/dacpac/fred-series-schema-v2.dacpac'

    
