name: Azure SQL Database Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to Azure SQL Database
      uses: azure/sql-action@v1
      with:
        server-name: final-economic-server
        server-admin-login: ${{ secrets.AZURE_DB_USER }}
        server-admin-password: ${{ secrets.AZURE_DB_PASS }}
        database-name: main_fred_db
        sql-file: ./database/fred-schema.sql
    
    - name: Run data update script
      run: node ./scripts/update-data.js
