name: FRED x Azure SQL Database Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to Azure SQL Database
      uses: azure/sql-action@v1.2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
    
